# Generated by Django 5.2 on 2026-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
