# Generated by Django 5.2 on 2026-08-18 17:02

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12, validators=[accounts.validators.validate_iranian_cellphone_number])),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'درحال بررسی'), ('resolved', 'حل شده'), ('cancled', 'کنسل شده')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
