# Generated by Django 5.2 on 2026-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newslettermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
