# Generated by Django 5.2 on 2026-08-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_newslettermodel_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='TicketModel',
        ),
    ]
