# Generated by Django 5.2 on 2026-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otptokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptokenmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
