# Generated by Django 5.2 on 2026-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otptokenmodel_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Profile/default/images.jpg', null=True, upload_to='profile/users'),
        ),
    ]
