# Generated by Django 5.2 on 2026-08-09 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_couponmodel_ordermodel_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 9, 7, 32, 12, 495004, tzinfo=datetime.timezone.utc)),
        ),
    ]
