# Generated by Django 5.2 on 2026-08-09 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_couponmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 9, 18, 29, 47, 846347, tzinfo=datetime.timezone.utc)),
        ),
    ]
