# Generated by Django 5.2 on 2026-08-09 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_couponmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 9, 18, 32, 56, 130922, tzinfo=datetime.timezone.utc)),
        ),
    ]
