# Generated by Django 5.2 on 2026-08-09 18:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_couponmodel_expired_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 9, 18, 33, 16, 383729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
