# Generated by Django 5.2 on 2026-08-10 10:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_couponmodel_expired_date_and_more'),
        ('payment', '0002_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentmodel'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 10, 10, 27, 4, 783575, tzinfo=datetime.timezone.utc)),
        ),
    ]
