# Generated by Django 5.2 on 2026-08-11 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermodel_payment_alter_couponmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 11, 14, 27, 54, 944168, tzinfo=datetime.timezone.utc)),
        ),
    ]
