# Generated by Django 5.2 on 2026-08-11 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_couponmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 11, 20, 8, 17, 889533, tzinfo=datetime.timezone.utc)),
        ),
    ]
