# Generated by Django 5.2 on 2026-08-14 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_couponmodel_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='slug',
            field=models.SlugField(default='free', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 14, 20, 50, 0, 13999, tzinfo=datetime.timezone.utc)),
        ),
    ]
