# Generated by Django 5.2 on 2026-08-17 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_couponmodel_slug_alter_couponmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expired_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
