# Generated by Django 5.2 on 2026-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('ref_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('response_json', models.JSONField(default=dict)),
                ('response_code', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paied', 'پرداخت شده'), ('canceled', 'لفو شده')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
