# Generated by Django 5.2 on 2026-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paied', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
