# Generated by Django 5.2 on 2026-08-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
