# Generated by Django 5.2 on 2026-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentmodel_response_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='authority_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
